### ISSUE TITLE
filemtime

### ISSUE THREAD

**Issue by trendoman** [fallingsprings/couch-add-ons#3]
Hi Tim,

I also met the "filemtime" warnings (**minify-js-css** addon)
I scratched the surface and it seems this function tries to work with non-existent (yet) **$output_file**. 

Maybe creating an empty one first (before anything) would solve the issue?

I understand from your forum's reply that you have warnings turned off, so we could stfu & do the same. However, maybe you'd want to have the logic streamlined.

Thanks and regards
Anton

**Comment by fallingsprings** [comment]
Anton, 
The issue was originally brought to my attention not because the **$output_file** was non-existent (yet), but because certain items in the list of things to be combined were not actually files. For instance, a chunk of inline code is stored and replaced in the list with a placeholder. The function would go through the list, dutifully check the _filemtime_ for this thing that was not a file, and throw the warning.

That has been corrected.

I hadn't considered the situation where the **$output_file** doesn't yet exist. It would only happen the very first time the developer uses the addon or if they delete the output file to force refresh. I have corrected the function to skip over comparing modification dates and go straight to creating the new combined file in the case where the **$output_file** is missing. Hopefully, that will put this _filemtime_ warning to rest.

Thanks for the help,
Tim

**Comment by trendoman** [comment]
Tim, 

Thanks for the update. Please check the block between lines 79-85 for similar issues. Curiously, at my first use of this addon I immediately defined the MINIFY_TIMESTAMP_QUERYSTRING and had the mentioned issue. I now see you found and fixed it in other places :)

Thanks for keeping it alive
Anton

**Comment by fallingsprings** [comment]
OK. Now I'm _pretty sure_ that I have addressed the filemtime warning issue. Please let me know if you spot any problems. Thanks.

**Comment by trendoman** [comment]
Thank you very much.
